// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// Define the KV namespace binding
interface Env {
    myUrlShortner_KV: KVNamespace
  }
