name = "shortner"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "myUrlShortner_KV", id = "252ae36d531745b3a1242846a2754867", preview_id = "252ae36d531745b3a1242846a2754867" }
]


[vars]
HOST_URL = "https://shortner.archie9211.workers.dev/"